---
title: "Vaccine Inequality"
author: "Gabriel Carrasco-Escobar"
date: "5/22/2021"
output: html_document
---

# Packages and Data

```{r}
library(tidyverse)
library(sf)
library(mapview)
library(spdep)
library(sp)
library(purrr)
library(leaflet)
library(RColorBrewer)

load("./Data_analysis_India.RData")

df3 <- df3 %>%
  rownames_to_column() %>%
  inner_join(df3 %>%
               st_set_geometry(NULL) %>%
               rownames_to_column() %>%
               distinct(cntrycode, dist.code, .keep_all = T) %>%
               select(rowname), by = "rowname")

```

# Visualization

```{r}
mapview(df3, zcol = "FIC")

mapview(df3, zcol = "PIC")
```

## Saptial Analysis

## Data wrangling

- Remove regions with no neighbours

```{r}
df3_sp <- as(df3, "Spatial")
IN_nb <- poly2nb(df3_sp)  #queen contiguity
summary(IN_nb)

df3_r <- df3 %>%
  rownames_to_column(var = "id") %>%
  filter(!(id %in% c(339, 417, 419, 551)))

# d <- df3_r %>%
#   st_set_geometry(NULL)

```


## Clustering

```{r}
df3_sp <- as(df3_r, "Spatial")
IN_nb <- poly2nb(df3_sp)  #queen contiguity
summary(IN_nb)

coords_IND<-coordinates(df3_sp) # coordinates
IN_w<-nb2listw(IN_nb) #weights style W - row standardized

moran.test(df3_sp$FIC,listw=IN_w)
moran.test(df3_sp$PIC,listw=IN_w)

breaks <- c(-Inf, -2.58, -1.96, -1.65, 1.65, 1.96, 2.58, Inf)
labels <- c("Low (99% confidence)", "Low (95% confidence)", "Low (90% confidence)", "PSU Not significant","High (90% confidence)", "High (95% confidence)", "High (99% confidence)")

w.getis <- df3_r %>%
  st_set_geometry(NULL) %>%
  nest() %>%
  crossing(var1 = c("FIC","PIC")) %>%
  mutate(data_sub = map2(.x = data, .y = var1, 
                         .f = ~dplyr::select(.x, .y, cntrycode, 
                                             dist.code) %>% 
                           rename(output = 1)),
         LISA = map(.x = data_sub, .f = ~localG(.x$output, IN_w)),
         clust_LISA = map(.x = LISA, .f = ~cut(.x, include.lowest = TRUE, 
                                               breaks = breaks, labels = labels,
                                               ordered_result = T))) %>%
  dplyr::select(data_sub, var1, LISA, clust_LISA) %>%
  unnest()

```

## Mapping

```{r}
map_fic <- df3_r %>%
  inner_join(w.getis %>% filter(var1 =="FIC"), 
             by = c("cntrycode", "dist.code")) %>%
  mutate(clust_LISA = fct_rev(clust_LISA))

mapview(map_fic, zcol ="clust_LISA", col.regions = brewer.pal(7, "RdBu"),
        layer.name = "LISA - FIC")

map_fic %>%
  ggplot(aes(fill = clust_LISA)) + 
  scale_fill_brewer(palette = "RdBu") + 
  theme_bw()


map_pic <- df3_r %>%
  inner_join(w.getis %>% filter(var1 =="PIC"), 
             by = c("cntrycode", "dist.code")) %>%
  mutate(clust_LISA = fct_rev(clust_LISA))

mapview(map_pic, zcol ="clust_LISA", col.regions = brewer.pal(7, "RdBu"),
        layer.name = "LISA - PIC")
  
```

